// This file is automatically generated. Do not modify it manually.
import { FirebaseOptions } from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
  apiKey: 'AIzaSyDvJmQb29YHfeC36UuK3-5Hjbg6ON3r9FI',
  authDomain: 'healthcheck-43bcp.firebaseapp.com',
  projectId: 'healthcheck-43bcp',
  storageBucket: 'healthcheck-43bcp.appspot.com',
  messagingSenderId: '858881830943',
  appId: '1:858881830943:web:d60d96a26f0bc7fe06252a',
};
